config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  resources :bands
  resources :albums, except: :index
  resources :tracks, except: :index

  resources :notes, only: [:create]

  root to: redirect("/users")
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id               :integer          not null, primary key
#  title            :string           not null
#  album_id         :integer          not null
#  bonus_or_regular :string           not null
#  lyrics           :text             not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Track < ActiveRecord::Base
  validates :title, :album_id, :bonus_or_regular, :lyrics, presence: true

  belongs_to :album,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: "Album"

  has_one :band,
    through: :album,
    source: :band

  has_many :notes

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :require_user!

  def new
    @track = Track.new
    @albums = Album.all
    render :new
  end

  def create
    @track = Track.new(track_params)
    @albums = Album.all

    if @track.save
      redirect_to bands_url
    else
      render :new
    end
  end

  def edit
    @track = Track.find(params[:id])
    @albums = Album.all
    render :edit
  end

  def update
    @track = Track.find(params[:id])
    @albums = Album.all
    if @track.update_attributes(track_params)
      redirect_to bands_url
    else
      render :edit
    end
  end

  def show
    @track = Track.find(params[:id])
    @album = @track.album
    render :show
  end

  def destroy
    @track = Track.find(params[:id])
    @track.destroy
    redirect_to bands_url
  end

  def track_params
    params.require(:track).permit(:title, :album_id, :bonus_or_regular, :lyrics)
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/edit.html.erb
<h3>Update Track "<%= @track.title %>"</h3>

<form action="<%= track_url(@track) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <%= auth_token %>

  <label for="track_title_id">Track Title</label>
  <input
    type="text"
    name="track[title]"
    id="track_title_id"
    value="<%= @track.title %>">
  <br>

  <label for="album_name_id">Album:</label>
  <select name="track[album_id]", id="album_name_id">
    <option></option>
    <% @albums.each do |album| %>
      <option
        <%= @track.album_id == album.id ? "selected" : "" %>
        value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="track[bonus_or_regular]"
    value="Bonus"
    id="bonus_or_regular_id"
    <%= @track.bonus_or_regular == "Bonus" ? "Regular" : "" %>>
  <label for="bonus_or_regular_id">Live</label>
  <input
    type="radio"
    name="track[bonus_or_regular]"
    value="Regular"
    id="bonus_or_regular_id"
    <%= @track.bonus_or_regular == "Regular" ? "checked" : "" %>>
  <label for="bonus_or_regular_id">Regular</label>
  <br>

  <label>
    Lyrics
    <textarea name="track[lyrics]"><%= @track.lyrics %></textarea>
  </label>
  <br>

  <input type="submit" value="Update Track Info!">
  </p>

</form>

app/views/tracks/new.html.erb
<h3>Create a Track!</h3>

<form action="<%= tracks_url %>" method="post">

  <%= auth_token %>

  <label for="track_title_id">Track Title</label>
  <input
    type="text"
    name="track[title]"
    id="track_title_id"
    value="<%= @track.title %>">
  <br>

  <label for="album_name_id">Album:</label>
  <select name="track[album_id]", id="album_name_id">
    <option></option>
    <% @albums.each do |album| %>
      <option
        <%= @track.album_id == album.id ? "selected" : "" %>
        value="<%= album.id %>">
        <%= album.title %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="track[bonus_or_regular]"
    value="Bonus"
    id="bonus_or_regular_id"
    <%= @track.bonus_or_regular == "Bonus" ? "Regular" : "" %>>
  <label for="bonus_or_regular_id">Live</label>
  <input
    type="radio"
    name="track[bonus_or_regular]"
    value="Regular"
    id="bonus_or_regular_id"
    <%= @track.bonus_or_regular == "Regular" ? "checked" : "" %>>
  <label for="bonus_or_regular_id">Regular</label>
  <br>

  <label>
    Lyrics
    <textarea name="track[lyrics]"><%= @track.lyrics %></textarea>
  </label>
  <br>

  <input type="submit" value="Create Track!">
  </p>

</form>

app/views/tracks/show.html.erb
<h3>Track Info</h3>
<%= link_to "Edit", edit_track_url(@track) %>
<br>
<br>

<li>Album: <%= link_to "#{@track.album.title}", album_url(@album) %></li>
<li>Track No.: <%= @track.id %></li>
<li>Title: <%= @track.title %></li>
<li>Type: <%= @track.bonus_or_regular %></li>
<li>Lyrics: <%= @track.lyrics %></li>
<li>Notes: </li>
  <% @track.notes.each do |note| %>
    <p><%= note.notes %></p>
  <% end %>
<br>

<%= render "notes/notes", track_id: @track.id %>

<%= button_to "Delete Track", @track, method: :delete %>