config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  resources :bands
  resources :albums, except: :index
  resources :tracks, except: :index

  resources :notes, only: [:create]

  root to: redirect("/users")
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :notes

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil if user.nil?

    if user.is_password?(password)
      user
    else
      nil
    end
  end

  def self.generate_session_token
    SecureRandom.base64(16)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user!, except: [:new, :create]

  def new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save!
      log_in_user!(@user)
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    render :show
  end

  def index
    @users = User.all
    render :index
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% if logged_in? %>
  <form action="<%= session_url %>" method="post">
    <%= auth_token %>
    <%= current_user.email %>
    <input name="_method" type="hidden" value="delete">
    <input type="submit" value="Log Out!">
  </form>
<% end %>

app/views/users/index.html.erb
<h3>All Users</h3>

<% @users.each do |user| %>
  <li><%= user.email %></li>
  <li><%= user.password_digest %></li>
  <li><%= user.session_token %></li>
  </p>
<% end %>

app/views/users/new.html.erb
<h3>Sign Up!</h3>

<form action="<%= users_url %>" method="post">

  <%= auth_token %>

  <label for="user_email">Email:</label>
  <input id="user_email" type="text" name="user[email]">
  </p>

  <label for="user_password">Password:</label>
  <input id="user_password" type="password" name="user[password]">
  </p>

  <input type="submit" value="Register">
  </p>

</form>

app/views/users/show.html.erb
<h3>Your Homepage</h3>

<li><%= @user.email %></li>
<li><%= @user.password_digest %></li>
<li><%= @user.session_token %></li>

<%= link_to "Check out the bands!", bands_url %>