config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  resources :bands
  resources :albums, except: :index
  resources :tracks, except: :index

  resources :notes, only: [:create]

  root to: redirect("/users")
end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id             :integer          not null, primary key
#  title          :string
#  band_id        :integer          not null
#  live_or_studio :string           not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Album < ActiveRecord::Base
  validates :title, :band_id, :live_or_studio, presence: true

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: "Band"

  has_many :tracks,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: "Track",
    dependent: :destroy


end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!

  def new
    @album = Album.new
    @bands = Band.all
    render :new
  end

  def create
    @album = Album.new(album_params)
    @bands = Band.all

    if @album.save
      redirect_to bands_url
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    @bands = Band.all
    render :edit
  end

  def update
    @album = Album.find(params[:id])
    @bands = Band.all
    if @album.update_attributes(album_params)
      redirect_to bands_url
    else
      render :edit
    end
  end

  def show
    @album = Album.find(params[:id])
    @band = @album.band
    render :show
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to bands_url
  end

  def album_params
    params.require(:album).permit(:title, :band_id, :live_or_studio)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<h3>Update Album "<%= @album.title %>"</h3>

<form action="<%= album_url(@album) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <%= auth_token %>

  <label for="album_title_id">Album Title</label>
  <input
    type="text"
    name="album[title]"
    id="album_title_id"
    value="<%= @album.title %>">
  <br>

  <label for="band_name_id">Band:</label>
  <select name="album[band_id]", id="band_name_id">
    <option></option>
    <% @bands.each do |band| %>
      <option
        <%= @album.band_id == band.id ? "selected" : "" %>
        value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="album[live_or_studio]"
    value="Live"
    id="live_or_studio_id"
    <%= @album.live_or_studio == "Live" ? "checked" : "" %>>
  <label for="live_or_studio_id">Live</label>
  <input
    type="radio"
    name="album[live_or_studio]"
    value="Studio"
    id="live_or_studio_id"
    <%= @album.live_or_studio == "Studio" ? "checked" : "" %>>
  <label for="live_or_studio_id">Studio</label>
  <br>

  <input type="submit" value="Update Album Info!">
  </p>

</form>

app/views/albums/new.html.erb
<h3>Create an Album!</h3>

<form action="<%= albums_url %>" method="post">

  <%= auth_token %>

  <label for="album_title_id">Album Title</label>
  <input
    type="text"
    name="album[title]"
    id="album_title_id"
    value="<%= @album.title %>">
  <br>

  <label for="band_name_id">Band:</label>
  <select name="album[band_id]", id="band_name_id">
    <option></option>
    <% @bands.each do |band| %>
      <option
        <%= @album.band_id == band.id ? "selected" : "" %>
        value="<%= band.id %>">
        <%= band.name %>
      </option>
    <% end %>
  </select>
  <br>

  <input
    type="radio"
    name="album[live_or_studio]"
    value="Live"
    id="live_or_studio_id"
    <%= @album.live_or_studio == "Live" ? "checked" : "" %>>
  <label for="live_or_studio_id">Live</label>
  <input
    type="radio"
    name="album[live_or_studio]"
    value="Studio"
    id="live_or_studio_id"
    <%= @album.live_or_studio == "Studio" ? "checked" : "" %>>
  <label for="live_or_studio_id">Studio</label>
  <br>

  <input type="submit" value="Create Album!">

</form>

app/views/albums/show.html.erb
<h3>Album Info</h3>
<%= link_to "Edit", edit_album_url(@album) %>
<br>
<br>

<li>Title: <%= @album.title %></li>
<li>Artist: <%= link_to "#{@album.band.name}", band_url(@band) %></li>
<li>Type: <%= @album.live_or_studio %></li>
<br>

<ul>
  <li>Tracks
    <% @album.tracks.each do |track| %>
      <p><%= link_to "#{track.title}", track_url(track) %></p>
    <% end %>
  </li>
</ul>
<br>

<%= button_to "Create New Track", new_track_url, method: :get %>
<%= button_to "Delete Album", @album, method: :delete %>