config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :index]
  resource :session, only: [:new, :create, :destroy]

  resources :bands
  resources :albums, except: :index
  resources :tracks, except: :index

  resources :notes, only: [:create]

  root to: redirect("/users")
end

app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: "Album",
    dependent: :destroy

  has_many :tracks,
    through: :albums,
    source: :tracks,
    dependent: :destroy


end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :require_user!

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      redirect_to bands_url
    else
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(band_params)
      redirect_to bands_url
    else
      render :edit
    end
  end

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  def band_params
    params.require(:band).permit(:name)
  end
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/views/bands/edit.html.erb
<h3>Update Band "<%= @band.name %>"</h3>

<form action="<%= band_url(@band) %>" method="post">
  <input type="hidden" name="_method" value="patch">

  <%= auth_token %>

  <label for="band_name">Band Name:</label>
  <input id="band_name" type="text" name="band[name]" value="<%= @band.name %>">
  </p>

  <input type="submit" value="Update Band Info!">
  </p>

</form>

app/views/bands/index.html.erb
<h3>Band List</h3>

<% @bands.each do |band| %>
  <li><%= link_to "#{band.name}", band_url(band) %></li>
  <div><%= link_to "Edit", edit_band_url(band) %></div>
  <div><%= button_to "Delete", band, method: :delete %></div>
<% end %>
<br>

<%= button_to "Create New Band!", new_band_url, method: :get %>

app/views/bands/new.html.erb
<h3>Create a Band!</h3>

<form action="<%= bands_url %>" method="post">

  <%= auth_token %>

  <label for="band_name">Band Name:</label>
  <input id="band_name" type="text" name="band[name]" value="<%= @band.name %>">
  </p>

  <input type="submit" value="Create Band!">
  </p>

</form>

app/views/bands/show.html.erb
<h3>Band Info</h3>
<%= @band.name %>
<%= link_to "Edit Info", edit_band_url(@band) %>

<ul>
  <li>Albums
    <% @band.albums.each do |album| %>
      <p><%= link_to "#{album.title}", album_url(album) %></p>
    <% end %>
  </li>
</ul>
<br>

<%= button_to "Create New Album!", new_album_url, method: :get %>

<%= link_to "<< All Bands", bands_url %>